/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazon.backend;

import amazon.backend.IO.*;
import amazon.backend.manager.AckManager;
import amazon.backend.manager.LogisticsManager;
import amazon.backend.manager.ResendManager;
import amazon.backend.manager.StatusManager;
import org.hibernate.SessionFactory;

import java.io.IOException;

public class App {
    private final int myWebPort = 2222;
    private final int myUpsPort = 6666;
    public static final String IP = "vcm-25372.vm.duke.edu";
    public static final int UPSPORT = 12345;
    public static final int AMAZONPORT = 23456;
    public static long WORLDID = 24;

    private SessionFactory sessionFactory;

    public App() throws IOException {
        sessionFactory = SingletonSessionFactory.getSessionFactory();
        UpsIO upsIO = UpsIO.newInstance(myUpsPort);
        WORLDID = upsIO.receiveConnectFromUps();
        WorldIO.newInstance(IP, AMAZONPORT, WORLDID);
        upsIO.sendConnectToUps();
        WebIO.newInstance(myWebPort);
        AckManager.newInstance(sessionFactory);
        LogisticsManager.newInstance();
        StatusManager.newInstance();
        ResendManager.newInstance();
        WebListener.newInstance(WebIO.getInstance(), LogisticsManager.getInstance());
        WorldListener.newInstance(WorldIO.getInstance()
                , AckManager.getInstance()
                , LogisticsManager.getInstance());
        UpsListener.newInstance(upsIO
                , LogisticsManager.getInstance()
                , StatusManager.getInstance());
    }

    public void start() throws IOException {
        Thread webListener = new Thread(WebListener.getInstance(), "Web Listener");
        Thread worldListener = new Thread(WorldListener.getInstance(), "World Listener");
        Thread upsListener = new Thread(UpsListener.getInstance(), "Ups Listener");
        Thread resendManager = new Thread(ResendManager.getInstance(), "Resend Manager");

        webListener.start();
        worldListener.start();
        upsListener.start();
        resendManager.start();
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        // In testing, I need a ups io
//        UpsWorldIO upsWorldIO = new UpsWorldIO(IP, UPSPORT);
//        upsWorldIO.sendConnect();
//        WORLDID = upsWorldIO.recvConnected();
//        Thread thread = new Thread(upsWorldIO);
//        thread.start();

        App app = new App();
        app.start();

        while(true);
    }
}
