/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazon.backend;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class App {

    public static SessionFactory sessionFactory;

    public static void main(String[] args) {
        sessionFactory = new Configuration().configure().buildSessionFactory();
    }
}
