/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazon.backend;

import amazon.backend.IO.WebIO;
import amazon.backend.IO.WebOutputListener;
import amazon.backend.IO.WorldIO;
import amazon.backend.IO.WorldOutputListener;
import amazon.backend.manager.AckManager;
import amazon.backend.manager.LogisticsManager;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import java.io.IOException;

public class App {

    private final int myWebPort = 2222;
    private final int myUpsPort = 6666;
    String ip = "vcm-25372.vm.duke.edu";
    int upsPort = 23456;
    int amazonPort = 12345;
    int worldId = 1;

    private SessionFactory sessionFactory;

    public App() throws IOException {
        sessionFactory = SingletonSessionFactory.getSessionFactory();
        WebIO.newInstance(myWebPort);
        System.out.println("Web connected");
        AckManager.newInstance(sessionFactory);
        LogisticsManager.newInstance(sessionFactory);
        WebOutputListener.newInstance(WebIO.getInstance(), LogisticsManager.getInstance());
        WorldOutputListener.newInstance(WorldIO.newInstance(ip, amazonPort, worldId), AckManager.getInstance());
    }

    public void start() throws IOException {
        Thread webListener = new Thread(WebOutputListener.getInstance());
        Thread worldListener = new Thread(WorldOutputListener.getInstance());

        webListener.start();
        worldListener.start();


    }

    public static void main(String[] args) throws IOException {
        App app = new App();
        app.start();
    }
}
